[build-system]
requires = ["hatchling", "PySimpleGui", "requests"]
build-backend = "hatchling.build"

[project]
name = "Phoenix-Project"
version = "0.0.1"
authors = [
  { name="Lonely-Dark", email="vlad10game@gmail.com" },
]
description = "GUI Version for Phoenix"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Lonely-Dark/Phoenix-Project"
"Bug Tracker" = "https://github.com/Lonely-Dark/Phoenix-Project/issues"